module suisage::vault {
    use sui::balance::{Self, Balance};
    use sui::coin::{Self, Coin};
    use sui::sui::SUI;
    use sui::event;

    // ===== Errors =====
    const EZeroDeposit: u64 = 0;
    const EInsufficientShares: u64 = 1;
    const EVaultPaused: u64 = 2;
    const EZeroWithdraw: u64 = 3;
    const EInsufficientLiquidity: u64 = 4;
    const EInvalidFeeBps: u64 = 5;

    // ===== Constants =====
    const BPS_BASE: u64 = 10000;
    const DEFAULT_PERFORMANCE_FEE_BPS: u64 = 1000; // 10% of profits

    // ===== Objects =====

    /// Shared vault holding all user deposits with performance fee tracking
    public struct Vault has key {
        id: UID,
        /// Address that created the vault (used for AdminCap access control)
        creator: address,
        /// Total SUI balance held
        balance: Balance<SUI>,
        /// Total shares outstanding
        total_shares: u64,
        /// Amount currently deployed to trading (tracked off-balance)
        deployed_amount: u64,
        /// Whether the vault is paused (emergency stop)
        paused: bool,
        /// Performance fee in basis points (e.g., 1000 = 10% of profits)
        performance_fee_bps: u64,
        /// High-water mark: highest NAV per share (scaled by 1e9 for precision)
        high_water_mark: u64,
        /// Accumulated fees available for admin withdrawal
        accrued_fees: Balance<SUI>,
        /// Total lifetime profit generated by the agent
        total_profit: u64,
        /// Total lifetime loss from agent trading
        total_loss: u64,
        /// Number of profit-taking events
        profit_events: u64,
    }

    /// Receipt NFT proving a user's deposit and share count
    public struct DepositReceipt has key, store {
        id: UID,
        vault_id: ID,
        shares: u64,
        deposited_amount: u64,
    }

    // ===== Events =====

    public struct DepositEvent has copy, drop {
        vault_id: ID,
        depositor: address,
        amount: u64,
        shares_minted: u64,
        total_shares: u64,
    }

    public struct WithdrawEvent has copy, drop {
        vault_id: ID,
        withdrawer: address,
        amount: u64,
        shares_burned: u64,
        total_shares: u64,
    }

    public struct PerformanceEvent has copy, drop {
        vault_id: ID,
        profit: u64,
        fee_taken: u64,
        new_high_water_mark: u64,
        nav_per_share: u64,
    }

    public struct FeeWithdrawnEvent has copy, drop {
        vault_id: ID,
        amount: u64,
        recipient: address,
    }

    // ===== Public functions =====

    /// Create a new shared vault with configurable performance fee
    public fun create_vault(ctx: &mut TxContext) {
        let vault = Vault {
            id: object::new(ctx),
            creator: tx_context::sender(ctx),
            balance: balance::zero(),
            total_shares: 0,
            deployed_amount: 0,
            paused: false,
            performance_fee_bps: DEFAULT_PERFORMANCE_FEE_BPS,
            high_water_mark: 1_000_000_000, // 1.0 scaled by 1e9 (initial NAV = 1:1)
            accrued_fees: balance::zero(),
            total_profit: 0,
            total_loss: 0,
            profit_events: 0,
        };
        transfer::share_object(vault);
    }

    /// Create vault with custom fee (for admin flexibility)
    public fun create_vault_with_fee(fee_bps: u64, ctx: &mut TxContext) {
        assert!(fee_bps <= 5000, EInvalidFeeBps); // Max 50% fee

        let vault = Vault {
            id: object::new(ctx),
            creator: tx_context::sender(ctx),
            balance: balance::zero(),
            total_shares: 0,
            deployed_amount: 0,
            paused: false,
            performance_fee_bps: fee_bps,
            high_water_mark: 1_000_000_000,
            accrued_fees: balance::zero(),
            total_profit: 0,
            total_loss: 0,
            profit_events: 0,
        };
        transfer::share_object(vault);
    }

    /// Deposit SUI into the vault, receive a DepositReceipt
    public fun deposit(
        vault: &mut Vault,
        coin: Coin<SUI>,
        ctx: &mut TxContext,
    ) {
        assert!(!vault.paused, EVaultPaused);
        let amount = coin::value(&coin);
        assert!(amount > 0, EZeroDeposit);

        // Calculate shares: if first deposit, 1:1. Otherwise proportional.
        let total_value = balance::value(&vault.balance) + vault.deployed_amount;
        let shares = if (vault.total_shares == 0 || total_value == 0) {
            amount
        } else {
            ((((amount as u128) * (vault.total_shares as u128)) / (total_value as u128)) as u64)
        };

        // Take the coin into the vault balance
        balance::join(&mut vault.balance, coin::into_balance(coin));
        vault.total_shares = vault.total_shares + shares;

        let vault_id = object::id(vault);

        // Mint receipt
        let receipt = DepositReceipt {
            id: object::new(ctx),
            vault_id,
            shares,
            deposited_amount: amount,
        };
        transfer::transfer(receipt, tx_context::sender(ctx));

        event::emit(DepositEvent {
            vault_id,
            depositor: tx_context::sender(ctx),
            amount,
            shares_minted: shares,
            total_shares: vault.total_shares,
        });
    }

    /// Withdraw SUI by burning a DepositReceipt (full or partial)
    public fun withdraw(
        vault: &mut Vault,
        receipt: DepositReceipt,
        shares_to_burn: u64,
        ctx: &mut TxContext,
    ) {
        assert!(!vault.paused, EVaultPaused);
        assert!(shares_to_burn > 0, EZeroWithdraw);
        assert!(shares_to_burn <= receipt.shares, EInsufficientShares);

        let total_value = balance::value(&vault.balance) + vault.deployed_amount;
        let withdraw_amount = ((((shares_to_burn as u128) * (total_value as u128)) / (vault.total_shares as u128)) as u64);

        // Revert if insufficient liquidity (deployed funds are not available)
        let available = balance::value(&vault.balance);
        assert!(withdraw_amount <= available, EInsufficientLiquidity);

        vault.total_shares = vault.total_shares - shares_to_burn;

        let vault_id = object::id(vault);

        // Handle receipt: if partial burn, update; if full burn, destroy
        let DepositReceipt { id, vault_id: _, shares, deposited_amount: _ } = receipt;
        if (shares_to_burn < shares) {
            // Create new receipt with remaining shares
            let new_receipt = DepositReceipt {
                id: object::new(ctx),
                vault_id,
                shares: shares - shares_to_burn,
                deposited_amount: 0, // original deposit tracking lost on partial
            };
            transfer::transfer(new_receipt, tx_context::sender(ctx));
        };
        object::delete(id);

        // Transfer withdrawn SUI to sender
        let withdrawn_balance = balance::split(&mut vault.balance, withdraw_amount);
        let withdrawn_coin = coin::from_balance(withdrawn_balance, ctx);
        transfer::public_transfer(withdrawn_coin, tx_context::sender(ctx));

        event::emit(WithdrawEvent {
            vault_id,
            withdrawer: tx_context::sender(ctx),
            amount: withdraw_amount,
            shares_burned: shares_to_burn,
            total_shares: vault.total_shares,
        });
    }

    /// Emergency withdraw - ignores pause, burns full receipt
    public fun emergency_withdraw(
        vault: &mut Vault,
        receipt: DepositReceipt,
        ctx: &mut TxContext,
    ) {
        let shares_to_burn = receipt.shares;
        assert!(shares_to_burn > 0, EZeroWithdraw);

        let total_value = balance::value(&vault.balance) + vault.deployed_amount;
        let withdraw_amount = ((((shares_to_burn as u128) * (total_value as u128)) / (vault.total_shares as u128)) as u64);

        let available = balance::value(&vault.balance);
        let actual_withdraw = if (withdraw_amount > available) { available } else { withdraw_amount };

        vault.total_shares = vault.total_shares - shares_to_burn;

        let DepositReceipt { id, vault_id: _, shares: _, deposited_amount: _ } = receipt;
        object::delete(id);

        let withdrawn_balance = balance::split(&mut vault.balance, actual_withdraw);
        let withdrawn_coin = coin::from_balance(withdrawn_balance, ctx);
        transfer::public_transfer(withdrawn_coin, tx_context::sender(ctx));

        event::emit(WithdrawEvent {
            vault_id: object::id(vault),
            withdrawer: tx_context::sender(ctx),
            amount: actual_withdraw,
            shares_burned: shares_to_burn,
            total_shares: vault.total_shares,
        });
    }

    // ===== Agent-only functions (called via agent_auth) =====

    /// Withdraw funds from vault for trading deployment (agent only)
    public(package) fun withdraw_for_deployment(
        vault: &mut Vault,
        amount: u64,
    ): Balance<SUI> {
        vault.deployed_amount = vault.deployed_amount + amount;
        balance::split(&mut vault.balance, amount)
    }

    /// Return funds from trading back to vault with profit/loss accounting
    public(package) fun return_from_deployment(
        vault: &mut Vault,
        mut funds: Balance<SUI>,
    ) {
        let returned_amount = balance::value(&funds);

        if (returned_amount > vault.deployed_amount) {
            // Profit case
            let profit = returned_amount - vault.deployed_amount;
            vault.total_profit = vault.total_profit + profit;
            vault.profit_events = vault.profit_events + 1;

            // Calculate performance fee on profit
            let fee_amount = (((profit as u128) * (vault.performance_fee_bps as u128)) / (BPS_BASE as u128)) as u64;

            if (fee_amount > 0 && fee_amount < returned_amount) {
                // Split fee from returned funds
                let fee_balance = balance::split(&mut funds, fee_amount);
                balance::join(&mut vault.accrued_fees, fee_balance);
            };

            // Update high-water mark
            let remaining_value = balance::value(&vault.balance) + balance::value(&funds);
            if (vault.total_shares > 0) {
                let nav_per_share = (((remaining_value as u128) * 1_000_000_000) / (vault.total_shares as u128)) as u64;
                if (nav_per_share > vault.high_water_mark) {
                    vault.high_water_mark = nav_per_share;
                };

                event::emit(PerformanceEvent {
                    vault_id: object::id(vault),
                    profit,
                    fee_taken: fee_amount,
                    new_high_water_mark: vault.high_water_mark,
                    nav_per_share,
                });
            };

            vault.deployed_amount = 0;
        } else if (returned_amount < vault.deployed_amount) {
            // Loss case
            let loss = vault.deployed_amount - returned_amount;
            vault.total_loss = vault.total_loss + loss;
            vault.deployed_amount = vault.deployed_amount - returned_amount;
        } else {
            // Break-even
            vault.deployed_amount = vault.deployed_amount - returned_amount;
        };

        balance::join(&mut vault.balance, funds);
    }

    /// Set paused state (package-level, controlled by admin_cap)
    public(package) fun set_paused(vault: &mut Vault, paused: bool) {
        vault.paused = paused;
    }

    /// Set performance fee (package-level, controlled by admin_cap)
    public(package) fun set_performance_fee(vault: &mut Vault, fee_bps: u64) {
        assert!(fee_bps <= 5000, EInvalidFeeBps);
        vault.performance_fee_bps = fee_bps;
    }

    /// Withdraw accrued fees (package-level, called via admin_cap)
    public(package) fun withdraw_fees(vault: &mut Vault, ctx: &mut TxContext): Coin<SUI> {
        let fee_balance = balance::withdraw_all(&mut vault.accrued_fees);
        let amount = balance::value(&fee_balance);

        event::emit(FeeWithdrawnEvent {
            vault_id: object::id(vault),
            amount,
            recipient: tx_context::sender(ctx),
        });

        coin::from_balance(fee_balance, ctx)
    }

    // ===== View functions =====

    public fun vault_balance(vault: &Vault): u64 {
        balance::value(&vault.balance)
    }

    public fun vault_total_shares(vault: &Vault): u64 {
        vault.total_shares
    }

    public fun vault_deployed_amount(vault: &Vault): u64 {
        vault.deployed_amount
    }

    public fun vault_paused(vault: &Vault): bool {
        vault.paused
    }

    public fun vault_creator(vault: &Vault): address {
        vault.creator
    }

    public fun receipt_shares(receipt: &DepositReceipt): u64 {
        receipt.shares
    }

    public fun receipt_vault_id(receipt: &DepositReceipt): ID {
        receipt.vault_id
    }

    public fun vault_performance_fee_bps(vault: &Vault): u64 {
        vault.performance_fee_bps
    }

    public fun vault_high_water_mark(vault: &Vault): u64 {
        vault.high_water_mark
    }

    public fun vault_accrued_fees(vault: &Vault): u64 {
        balance::value(&vault.accrued_fees)
    }

    public fun vault_total_profit(vault: &Vault): u64 {
        vault.total_profit
    }

    public fun vault_total_loss(vault: &Vault): u64 {
        vault.total_loss
    }

    public fun vault_total_value(vault: &Vault): u64 {
        balance::value(&vault.balance) + vault.deployed_amount
    }

    public fun vault_nav_per_share(vault: &Vault): u64 {
        if (vault.total_shares == 0) {
            1_000_000_000 // 1.0
        } else {
            let total_value = balance::value(&vault.balance) + vault.deployed_amount;
            (((total_value as u128) * 1_000_000_000) / (vault.total_shares as u128)) as u64
        }
    }
}
